// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonthlyCompanyBudget.Data;

#nullable disable

namespace MonthlyCompanyBudget.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MonthlyCompanyBudget.Core.Entities.BudgetItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BudgetItemTypes");
                });

            modelBuilder.Entity("MonthlyCompanyBudget.Core.Entities.MonthlyBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MonthlyBudgets");
                });

            modelBuilder.Entity("MonthlyCompanyBudget.Core.Entities.MonthlyBudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActualValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("BudgetItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonthlyBudgetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyBudgetId");

                    b.ToTable("MonthlyBudgetItems");
                });

            modelBuilder.Entity("MonthlyCompanyBudget.Core.Entities.MonthlyBudgetItem", b =>
                {
                    b.HasOne("MonthlyCompanyBudget.Core.Entities.MonthlyBudget", null)
                        .WithMany("Items")
                        .HasForeignKey("MonthlyBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonthlyCompanyBudget.Core.Entities.MonthlyBudget", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
