// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeeklyTimesheet.Infrastructure;

#nullable disable

namespace WeeklyTimesheet.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219073317_AddRateColumnsToTimesheetTable")]
    partial class AddRateColumnsToTimesheetTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("WeeklyTimesheet.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WeeklyTimesheet.Core.Entities.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HolidayLeaveRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RegularRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SickLeaveRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VacationLeaveRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("WeeklyTimesheet.Core.Entities.TimesheetLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DayOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<int>("HolidayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OvertimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SickMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesheetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VacationMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetId");

                    b.ToTable("TimesheetLogs");
                });

            modelBuilder.Entity("WeeklyTimesheet.Core.Entities.Employee", b =>
                {
                    b.HasOne("WeeklyTimesheet.Core.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("WeeklyTimesheet.Core.Entities.Timesheet", b =>
                {
                    b.HasOne("WeeklyTimesheet.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WeeklyTimesheet.Core.Entities.TimesheetLog", b =>
                {
                    b.HasOne("WeeklyTimesheet.Core.Entities.Timesheet", null)
                        .WithMany("Logs")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeeklyTimesheet.Core.Entities.Timesheet", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
